config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'account' => 'static_pages#account'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'get_password' => 'sessions#get_password'
  post 'get_password' => 'sessions#new_password'
  get    'profile' => 'users#show'
  post 'statement' => 'payments#statement'
  post 'make_payment' => 'payments#make_payment'
  post 'update_user' => 'users#update_user'
  get 'change_password' => 'users#change_password'
  post 'update_password' => 'users#update_password'
  post 'create_invoice' => 'invoices#create_invoice'
  resources :credits, only: [:new, :create]
  resources :banks, only: [:new, :create]
  resources :invoices
  resources :accounts
  resources :records
  resources :payments
  resources :users


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:home, :account]

  include InvoiceFiltering
  include InvoicesHelper

  def home
    if logged_in?
      user = User.new

      @user = user.get_user(session[:user_id])
      @latest_invoice = user.get_latest_invoice(session[:user_id])
      latest_time = create_time(@latest_invoice[:create_time_stamp]) if @latest_time
      @credit_data = user.previous_due(session[:user_id], latest_time)

      @payment_latest = Payment.new.get_latest_payment(current_user[:user_id])
      @order = Order.new.latest_order(current_user[:user_id])
      @order_type = @order.class

      @payments = Payment.new.get_payment_by_date(current_user[:user_id])
      @payments_data = []
      @payments_data = @payments.map{|m| [ time_format(Date.strptime(m.split('@').last)), m.split('@').first.to_i]}
      @payment_list = @payments_data.sort{ |a, b| b[1] <=> a[1] }
      @payment = Payment.new

      @invoices_data = invoices.map { |e| [time_format(e[:create_time_stamp]), e[:id]] }
      @invoice_list = @invoices_data.sort{ |a, b| b[1] <=> a[1]}
    end
  end



  def account
    user = User.new
    @user = user.contact
    @userdata = user.get_user
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
    <h2>I am sukanta</h2>
    I am a developer. I like ruby most. Ruby on Rails is my favourite web framework.
</p>

app/views/static_pages/account.html.erb
<%= @user %> </br></br>
<%= @userdata %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact page</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is a helper page of Toy application</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Dashboard') %>

<div class="page-header">
  <h1><i class="fa fa-tachometer"></i>  Dashboard</h1>
</div>
  <% if logged_in? && @user[:role] == "Customer" %>
  <%#= @latest_invoice %> <br>
  <%#= @credit_data[0] %>

  <div class="row">
    <p> <h3 class="bill"> Billing  <span class=" <%= label_color(@user[:status]) %>"> <%= @user[:status] %></span></h3></p>
    <div class="col-xs-6 ">

          <div class="thumbnail">
          <div class="caption">
          <dl class="dl-special">
            <dt><small>Account name :</small></dt>
            <dd><%= full_name(@user[:contact][:first_name], @user[:contact][:last_name])%> </dd>
            <dt><small>Account Number :</small></dt>
            <dd><%= @user[:user_id] %></dd>
            <dt><small>Service Address :</small></dt>
            <dd>
               <address>
                 <%= @user[:contact][:address1] %></br>
                 <%= @user[:contact][:address2] if @user[:contact][:address2] %>
                 <%= @user[:contact][:postal_code] %> - <%= @user[:contact][:city] %>,  <%= @user[:contact][:state_province] %>, USA
               </adress>
             </dd>
          </dl>
        </div>


      </div>
    </div>
    <div class="col-xs-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <p><small><i class="fa fa-calendar-check-o"></i> <em>Next Invoice Date :</em> <%= time_format( @user[:next_invoice_date]) if @user[:next_invoice_date] %></small></p>
          <div class="col-xs-6">
            <%= link_to '<i class="fa fa-credit-card"></i> Pay with credit card'.html_safe, new_credit_path, :class => "btn pull-left btn-danger", :id => "pay_link" %>
          </div>
          <div class="col-xs-6">
            <%= link_to '<i class="fa fa-university"></i> Pay with ACH(Bank)'.html_safe, new_bank_path, :class => "btn btn-danger", :id => "pay_link" %>
          </div>
        </div>
        <div class="panel-footer"><small> Please pay your outstanding bills if you have unpaid invoices</small></div>
      </div>



    </div>
  </div>
  <div class="row">

    <div class="col-xs-3">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-usd"></i> Last payment</h3>
        </div>
        <div class="panel-body">
          <% if @payment_latest %>
           <%= number_to_currency(@payment_latest[:amount],   precision: 2) %> (<%= @payment_latest[:method] %>)</br>
           <small> Applied : <%= time_format(@payment_latest[:payment_date]) %></small></small>
          <% else %>
            "No payment"
          <% end %>
        </div>
     </div>
    </div>
    <div class="col-xs-3">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-usd"></i> Past Due Balance</h3>
        </div>
        <div class="panel-body">
         <%#= number_to_currency(@user[:carried_balance].to_f,   precision: 2) %>
         <%= number_to_currency(@credit_data[0].to_f,   precision: 2) %>
        </div>
     </div>
    </div>
    <div class="col-xs-3">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-usd"></i> Current Charges <span class=" <%= status_invoice @latest_invoice[:status_id] if @latest_invoice  %>"> <%= status_print @latest_invoice[:status_id] if @latest_invoice %></span></h3>
        </div>
        <div class="panel-body">
          <% if @latest_invoice %>
            <%= number_to_currency(@latest_invoice[:balance], precision: 2) %> </br>
            <small> Due Date : <%= time_format(@latest_invoice[:due_date])  %></small>
          <% else %>
            "No chrages"
          <% end %>
        </div>
     </div>
    </div>
    <div class="col-xs-3">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-usd"></i> Total Balance</h3>
        </div>
        <div class="panel-body">
         <%= number_to_currency(@user[:owing_balance], precision: 2) %></br>
         <small>  <%= "Due Date : " + time_format(@latest_invoice[:due_date]) if @latest_invoice %></small>
        </div>
     </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <% if @order %>
            <% if @order.instance_of? Array  %>
              <h3 class="panel-title">Current plan </h3>
            <% else %>
              <h3 class="panel-title">Current plan <span class="badge"> <%= @order[:billing_type_str] %> </span>
              <small> <u> Active since: <%= time_format(@order[:active_since]) %></u></small></h3>
            <% end %>
          <% end %>
        </div>
        <div class="panel-body">
         <% if @order %>
           <% if @order.instance_of? Array %>
             <% @order.each do |latest_order| %>
               <small>Order id: <%= latest_order[:id]%> <span class="badge"> <%= latest_order[:billing_type_str] %> </span>Active since: <%= time_format(latest_order[:active_since]) %></small>
               <table class="table">
                  <tr>
                    <th> Item </th>
                    <th>Amount </th>
                  </tr>
                  <% latest_order[:order_lines].each do |item| %>
                    <tr>
                      <td> <%= item[:description]%> </td>
                      <td><%= number_to_currency( item[:amount] )%> </td>
                    </tr>
                  <% end %>
                </table>
              <% end %>
            <% else %>
              <small>Order id: <%= @order[:id]%> </small>
              <table class="table">
                <tr>
                  <th> Item </th>
                  <th>Amount </th>
                </tr>
                <% @order[:order_lines].each do |item| %>
                  <tr>
                    <td> <%= item[:description]%> </td>
                    <td><%= number_to_currency( item[:amount] )%> </td>
                  </tr>
                <% end %>
              </table>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>


      <div class="col-xs-4">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Invoice Detail</h3>
          </div>
          <div class="panel-body">
            <%= form_tag create_invoice_url do %>
              <%= select_tag( :id, options_for_select(@invoice_list) ) %>
              <%= submit_tag 'Invoice Detail', class: "button" %>
            <% end %>
          </div>
       </div>
      </div>

         <div class="col-xs-4">
           <div class="panel panel-primary">
             <div class="panel-heading">
               <h3 class="panel-title">Payment Detail</h3>
             </div>
             <div class="panel-body">
               <%= form_tag statement_url do %>
                 <%= select_tag(:id, options_for_select(@payment_list) ) %>
                 <%= submit_tag 'Payment Detail', class: "button" %>
               <% end %>
             </div>
          </div>
         </div>


  </div>

<% else %>
  <div class= "center jumbotron">
    <h1>Billing Portal</h1>
    <h2>[This portal is only for customer use]</h2>
      <h2>Go to nbilling to manage your billing <a href="https://nbilling.imeet.biz">nBilling</h2></a>

  </div>

<% end %>