config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'account' => 'static_pages#account'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'get_password' => 'sessions#get_password'
  post 'get_password' => 'sessions#new_password'
  get    'profile' => 'users#show'
  post 'statement' => 'payments#statement'
  post 'make_payment' => 'payments#make_payment'
  post 'update_user' => 'users#update_user'
  get 'change_password' => 'users#change_password'
  post 'update_password' => 'users#update_password'
  post 'create_invoice' => 'invoices#create_invoice'
  resources :credits, only: [:new, :create]
  resources :banks, only: [:new, :create]
  resources :invoices
  resources :accounts
  resources :records
  resources :payments
  resources :users


end

app/models/user.rb
class User
  attr_reader :user_id
    def initialize
      client_d = Client.new
      @client = client_d.client
    end

    def user_id(username)
      response = @client.call(:get_user_id, message: { username: username})
      if response.success?
        @user_id = response.to_array(:get_user_id_response, :return).first
      end
    end


   def authenticate(user_id, password)
     response = @client.call(:authenticate, message: {user_id: user_id, password: password})
     if response.success?
       data = response.to_array(:authenticate_response, :return).first
     end
   end
   def get_contact(user_id)
     contact_res = @client.call(:get_user_contacts_ws, message: { user_id: user_id })
     if contact_res.success?
       data = contact_res.to_array(:get_user_contacts_ws_response,:return).first

     end
   end

   def get_user(user_id)
     response = @client.call(:get_user_ws, message: { user_id: user_id})
     if response.success?
       @user = response.to_array(:get_user_ws_response, :return).first
     end
   end

   def update_contact(user_id, contact)
     response = @client.call(:update_user_contact, message: { user_id: user_id, type_id: 20, contact: contact })
    #  if response.success?
    #    @user = response.to_array(:get_user_ws_response, :return).first
    #  end
   end
   def update_password(user)
     response = @client.call(:update_user_password, message: { user: user })
   end
   def get_password(username)
     response = @client.call(:get_new_password, message: {  entity_id: 10.to_s, username: username })
     if response
       @data = response
     end
   end
   def get_latest_invoice(user_id)
     invoice_data = @client.call(:get_latest_invoice, message: { user_id: user_id})
     if invoice_data.success?
       data = invoice_data.to_array(:get_latest_invoice_response, :return).first
       @invoice_data = data
     end
   end
   def get_order(id)
     order_data = @client.call(:get_order, message: { order_id: id})
     if order_data.success?
       data = order_data.to_array(:get_order_response, :return).first
       @order_data = data
     end
   end
   def previous_due(user_id, last_invoice_date)
     response = @client.call(:retrive_user_payment_balance, message: {user_id: user_id, date: last_invoice_date})
     if response.success?
       data = response.to_array(:retrive_user_payment_balance_response, :return)
     end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:change_password]

  def index

  end

  def show
    @user = User.new.get_user(params[:id])
  end

  def new
    @user = User.new
  end
  def change_password

  end
  def edit
    @contact = User.new.get_contact(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email for account activation"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update_user
    #puts params[:user]
    contact = {:first_name => params[:user][:first_name],
               :last_name => params[:user][:last_name],
               :email => params[:user][:email],
               :organization_name => params[:user][:organization_name],
               :phone_area_code => params[:user][:phone_area_code],
               :phone_country_code => params[:user][:phone_country_code],
               :phone_number => params[:user][:phone_number],
               :social_security_code1 => params[:user][:social_security_code1],
               :social_security_code2 => params[:user][:social_security_code2],
               :social_security_code3 => params[:user][:social_security_code3],
               :address1 => params[:user][:address1],
               :address2 => params[:user][:address2],
               :postal_code => params[:user][:postal_code],
               :city => params[:user][:city],
               :state_province => params[:user][:state_province],
               :include => params[:user][:include]
             }
    if User.new.update_contact(session[:user_id], contact)
      flash[:success] = "Profile updated"
      redirect_to user_path(session[:user_id])

     else
       render 'edit'
     end
  end

 def update_password
    puts params[:user]

    if (!params[:user][:new_password].empty? && (params[:user][:new_password] == params[:user][:verify_password]))

       user = { :user_id => params[:user][:user_id],
                :user_name => params[:user][:user_name],
                :language_id => params[:user][:language_id],
                :role => params[:user][:role],
                :main_role_id => params[:user][:main_role_id],
                :language => params[:user][:language],
                :status_id => params[:user][:status_id],
                :subscriber_status_id => params[:user][:subscriber_status_id],
                :currency_id => params[:user][:currency_id],
                :password => params[:user][:new_password],
                :contact => { :organization_name => params[:user][:organization_name] }

              }
        if User.new.update_password(user)
          flash[:success] = "Password updated"
          redirect_to user_path(session[:user_id])

         end
       else
        flash[:danger] = "New password and Verify password must be same but not empty!!"
        redirect_to change_password_path
      end


 end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  private

    def set_user
      @user = User.new.get_user(session[:user_id])
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.new.get_user(current_user[:user_id])
      redirect_to root_url unless current_user?(@user)
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end

end

app/helpers/user_helper.rb
module UserHelper
  def delivery_method(id)
    id = id.to_i
    if id == 1
     "Email"
   elsif id == 2
     "Email and Papper"
   else
     "Paper"
   end
  end

  def notification(include)
    if include == true
      "is ON"
    else
      "is OFF"
    end
  end
end

app/views/users/_form.html.erb
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      <%= f.text_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation, 'Confirm' %>
      <%= f.password_field :password_confirmation %>
      
      

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    |<%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure!" } %>
  <% end %>
</li>

app/views/users/change_password.html.erb
<%#= @user.inspect %>
<% provide(:title, "Change password") %>

<div class="page-header">
  <h1>Change Password </h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= form_for(:user, url: update_password_path, :html => {class: "form-horizontal"}) do |f| %>
     <div class="form-group">
       <%= f.label :new_password, :class => "control-label col-xs-4" %>
       <div class="col-xs-8">
         <%= f.password_field :new_password, :class =>"form-control" %>
       </div>
     </div>
     <div class="form-group">
       <%= f.label :verify_password, :class => "control-label col-xs-4" %>
       <div class="col-xs-8">
         <%= f.password_field :verify_password, :class =>"form-control" %>
       </div>
     </div>
     <%= f.hidden_field :user_id , :value => @user[:user_id] %>
     <%= f.hidden_field :user_name , :value => @user[:user_name] %>
     <%= f.hidden_field :language_id , :value => @user[:language_id] %>
     <%= f.hidden_field :status_id , :value => @user[:status_id] %>
     <%= f.hidden_field :subscriber_status_id , :value => @user[:subscriber_status_id] %>
     <%= f.hidden_field :currency_id , :value => @user[:currency_id] %>
     <%= f.hidden_field :organization_name , :value => @user[:contact][:organization_name] %>
     <%= f.hidden_field :role , :value => @user[:role] %>
     <%= f.hidden_field :main_role_id , :value => @user[:main_role_id] %>
     <%= f.hidden_field :language , :value => @user[:language] %>

     <div class="form-group">
       <div class="col-sm-offset-4 col-sm-8">
         <%= f.submit "Update Password", class: "btn btn-primary" %>
       </div>
     </div>
   <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Update profile of #{full_name(@contact[:first_name], @contact[:last_name])}") %>

<div class="page-header">
  <h1>Profile Update <small> <%= full_name(@contact[:first_name], @contact[:last_name]) %></small></h1>
</div>
<div class="row">
   <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: update_user_path, :html => {class: "form-horizontal"}) do |f| %>
      <div class="form-group">
        <%= f.label :first_name, :class => "control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.text_field :first_name, :value => @contact[:first_name], :class =>"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :last_name, :class => "control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.text_field :last_name, :value => @contact[:last_name], :class =>"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, :class => "control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.text_field :email, :value => @contact[:email], :class =>"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :organization_name, :class => "control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= f.text_field :organization_name, :value => @contact[:organization_name], :class =>"form-control" %>
        </div>
      </div>



      <%= f.hidden_field :phone_area_code , :value => @contact[:phone_area_code] %>
      <%= f.hidden_field :phone_country_code , :value => @contact[:phone_country_code] %>
      <%= f.hidden_field :phone_number , :value => @contact[:phone_number] %>



      <%= f.hidden_field :social_security_code1 , :value => @contact[:social_security_code1] %>
      <%= f.hidden_field :social_security_code2 , :value => @contact[:social_security_code2] %>
      <%= f.hidden_field :social_security_code3 , :value => @contact[:social_security_code3] %>



      <%= f.hidden_field :address1 , :value => @contact[:address1] %>

      <%= f.hidden_field :address2 , :value => @contact[:address2] %>

      <%= f.hidden_field :postal_code , :value => @contact[:postal_code] %>

      <%= f.hidden_field :city , :value => @contact[:city] %>

      <%= f.hidden_field :state_province , :value => @contact[:state_province] %>
      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <div class="checkbox">
            <label>
              <%= f.check_box(:include, {checked: true}) %> Include in Notification
            </label>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <%= f.submit "Update Account", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>

  </div>
</div>


<%#= @contact %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1> All Users </h1>
<%= will_paginate %>
<ul class= "users">
 <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     
      <%= render 'form', f: f %>
      <%= f.submit "Create Account", class: "brt btn-primary" %>
    <% end %>  
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, full_name(@user[:contact][:first_name], @user[:contact][:last_name])) %>

<%#= @user %>

<div class="page-header">
  <h1>Billing profile <small> <%= full_name(@user[:contact][:first_name], @user[:contact][:last_name]) %> | <%= @user[:user_id] %></small></h1>
</div>
<div class="col-md-8 col-md-offset-2">
  <p class="bg-warning custom"> If you want to change your service address and Billing method please call us at 987590214</p>
</div>
<div class="row">
  <div class="col-xs-6 ">
    <div class="panel panel-primary">
       <div class="panel-heading">
         <h3 class="panel-title">Profile summary  <span class=" <%= label_color(@user[:status]) %>"> <%= @user[:status] %></span></h3>
       </div>
       <div class="panel-body">
         <dl class="dl-special">
           <dt>Account name </dt>
           <dd><%= full_name(@user[:contact][:first_name], @user[:contact][:last_name]) %> </dd>
           <dt>Account Number </dt>
           <dd><%= @user[:user_id] %></dd>
           <dt>Login </dt>
           <dd><%= organization_name(@user[:user_name]) %></dd>
           <dt>Organization Name </dt>
           <dd><%= organization_name(@user[:contact][:organization_name]) %></dd>
           <dt>Phone Number </dt>
           <dd><%= "#{@user[:contact][:phone_country_code]} - #{@user[:contact][:phone_area_code]} - #{@user[:contact][:phone_number]}"  %></dd>
           <dt>Social security</dt>
           <dd><%= social_security(@user[:contact][:social_security_code1], @user[:contact][:social_security_code2], @user[:contact][:social_security_code3]) %>
           </dd>
           <dt>Email </dt>
           <dd><%= @user[:contact][:email] %> </dd>
           <dt>Service Address </dt>
           <dd>
              <address>
              <strong> <%= @user[:contact][:address1]%> </strong></br>
              <%= @user[:contact][:address2] if @user[:contact][:address2] %>
              <%= @user[:contact][:postal_code] %> - <%= @user[:contact][:city] %>,  <%= @user[:contact][:state_province] %>, USA
              </adress>
            </dd>
         </dl>
       </div>
    </div>
  </div>
  <div class="col-xs-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Account Info  (Owed balance : <%= number_to_currency(@user[:owing_balance],   precision: 2) %>)</h3>
      </div>
      <div class="panel-body">
        <ul class="list-group">
          <li class="list-group-item"> Account created :</em> <%= time_format(@user[:create_datetime]) %>
          <li class="list-group-item"> Last status change :</em> <%= time_format(@user[:last_status_change]) %>
          <li class="list-group-item"> Next invoice :</em> <%= time_format(@user[:next_invoice_date]) %>
          <li class="list-group-item"> Payment method :</em> <%= time_format(@user[:credit_card][:expiry]) if @user[:credit_card] %></li>
          <li class="list-group-item"> Invoice Delivery method :</em> <%= delivery_method(@user[:invoice_delivery_method_id])%></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">

  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">  Bill Ready and Payment Notifications <span class="badge"><%= notification(@user[:contact][:include])%></span></h3>
      </div>
      <div class="panel-body">

        Get notified when your bill is ready to view and when your payment is successfully received. You will always receive these notifications by email to your billing email address.</br></br>

        Notification <%= notification(@user[:contact][:include])%></br>
        EMAIL
        <p class="pull-right"> <%= link_to "Change Settings", edit_user_path(session[:user_id]), class: "btn btn-primary" %> </p>
        <%= @user[:contact][:email] %>
      </div>
    </div>
  </div>
</div>
<%#= @user %>

app/views/users/show_follow.html.erb
<% provide( :title, @title ) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "View my profile", @user %></span>
      <span><b>Microposts: <%= @user.microposts.count %></b></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for( user, size: 30 ), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>