config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'account' => 'static_pages#account'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'get_password' => 'sessions#get_password'
  post 'get_password' => 'sessions#new_password'
  get    'profile' => 'users#show'
  post 'statement' => 'payments#statement'
  post 'make_payment' => 'payments#make_payment'
  post 'update_user' => 'users#update_user'
  get 'change_password' => 'users#change_password'
  post 'update_password' => 'users#update_password'
  post 'create_invoice' => 'invoices#create_invoice'
  resources :credits, only: [:new, :create]
  resources :banks, only: [:new, :create]
  resources :invoices
  resources :accounts
  resources :records
  resources :payments
  resources :users


end

app/models/payment.rb
class Payment

  def client
    Client.new.client
  end
   def get_latest_payment(user_id)
     response = client.call(:get_latest_payment, message: { user_id: user_id })
     if response.success?
       data = response.to_array(:get_latest_payment_response, :return).first
     end
   end
   def get_all_payment(user_id)
     response = client.call(:get_last_payments, message: { user_id: user_id, number: 1000 })
     if response.success?
       data = response.to_array(:get_last_payments_response, :return)
     end
   end
   def get_payment_by_date( user_id )
     response = client.call(:retrive_payment_ids_with_date, message: { user_id: user_id })
     if response.success?
       data = response.to_array(:retrive_payment_ids_with_date_response, :return)
     end
   end
   def get_payment(id)
     response = client.call(:get_payment, message: { payment_id: id })
     if response.success?
       data = response.to_array(:get_payment_response, :return).first
     end
   end
   def get_unpaid_invoices(user_id)
     response = client.call(:get_unpaid_invoices, message: { user_id: user_id })
     if response.success?
       data = response.to_array(:get_unpaid_invoices_response, :return)
     end
   end

   def process_payment(payment)
     response = client.call(:process_payment, message: { payment: payment })
     if response.success?
       data = response.to_array(:process_payment_response, :return).first
     end
   end
   private
    def method_type?
      method_id == 1
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :logged_in_user, only:[:index, :show, :new]
  #include InvoiceFiltering
  def index

    Rails.cache.fetch("#{session[:user_id]}/all_payments", expires_in: 12.hours) do
      @all_payments = Payment.new.get_all_payment(current_user[:user_id])
      @payments = []

      @all_payments.each do |payment|
        @payments << Payment.new.get_payment(payment.to_i)
      end
    end
  end
# its tests code and changing shit
  def statement
    @payment_id = params[:id]
    @statement = Payment.new.get_payment(@payment_id)
    puts @payment_id
  end

  def show
    @statement = Payment.new.get_payment(params[:id])
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
  def result id
    if id.to_i == 1
     "successfull"
    elsif id.to_i == 2
     "Failed"
    elsif id.to_i == 3
      "Processor Unavailable"
    elsif id.to_i == 4
    "Entered"
    end
  end
end

app/views/payments/_payment_detail.html.erb
<%#= @payment_id %>

  <div class="col-md-6 col-md-offset-3">


    <table class="table table-hover">

      <tr>
        <td>
          Payment Id
        </td>
        <td><%= @statement[:id] %></td>
      </tr>
      <tr>
        <td>
          Payment Date
        </td>
        <td><%= time_format(@statement[:payment_date]) %></td>
      </tr>
      <tr>
        <td>
          Payment Amount
        </td>
        <td><%= number_to_currency(@statement[:amount]) %></td>
      </tr>
      <tr>
        <td>
          Payment Status
        </td>
        <td><%= result(@statement[:result_id]) %></td>
      </tr>
      <tr>
        <td>
          Payment Method
        </td>
        <td><%= @statement[:method] %></td>
      </tr>
      <tr>
        <td>
          Remaining Balance
        </td>
        <td><%= number_to_currency(@statement[:balance].to_f) %></td>
      </tr>
      <% if @statement[:authorization_id] %>
        <tr>
          <td>
            Response code
          </td>
          <td><%= @statement[:authorization_id][:code1] %></td>
        </tr>
        <tr>
          <td>
            Payemnt Processor
          </td>
          <td><%= @statement[:authorization_id][:processor] %></td>
        </tr>
        <tr>
          <td>
            Response Message
          </td>
          <td><%= @statement[:authorization_id][:response_message] %></td>
        </tr>
      <% end %>
      <tr>
        <td>
          Linked Invoices
        </td>
        <td>
          <% if @statement[:invoice_ids]!= nil %>
          <% if @statement[:invoice_ids].kind_of?(Array) %>
            <%= @statement[:invoice_ids].map{|i| link_to i, invoice_path(i)}.join(' , ').html_safe %>
          <% else %>
            <%= link_to @statement[:invoice_ids], invoice_path(@statement[:invoice_ids]) %>
          <% end %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>

<%#= @statement %>
<%#= @statement[:invoice_ids].kind_of?(Array) %>

app/views/payments/_payment_details.html.erb
<%#= @payment_id %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <p> <b>Payment Details </b></p>
    <table class="table table-hover">

      <tr>
        <td>
          Payment Id
        </td>
        <td><%= @statement[:id] %></td>
      </tr>
      <tr>
        <td>
          Payment Date
        </td>
        <td><%= time_format(@statement[:payment_date]) %></td>
      </tr>
      <tr>
        <td>
          Payment Amount
        </td>
        <td><%= number_to_currency(@statement[:amount]) %></td>
      </tr>
      <tr>
        <td>
          Payment Status
        </td>
        <td><%= result(@statement[:result_id]) %></td>
      </tr>
      <tr>
        <td>
          Payment Method
        </td>
        <td><%= @statement[:method] %></td>
      </tr>
      <tr>
        <td>
          Remaining Balance
        </td>
        <td><%= number_to_currency(@statement[:balance].to_f) %></td>
      </tr>
      <% if @statement[:authorization_id] %>
        <tr>
          <td>
            Response code
          </td>
          <td><%= @statement[:authorization_id][:code1] %></td>
        </tr>
        <tr>
          <td>
            Payemnt Processor
          </td>
          <td><%= @statement[:authorization_id][:processor] %></td>
        </tr>
        <tr>
          <td>
            Response Message
          </td>
          <td><%= @statement[:authorization_id][:response_message] %></td>
        </tr>
      <% end %>
      <tr>
        <td>
          Linked Invoices
        </td>
        <td>
          <% if @statement[:invoice_ids]!= nil %>
            <% if @statement[:invoice_ids].kind_of?(Array) %>
              <%= @statement[:invoice_ids].map{|i| link_to i, invoice_path(i)}.join(' , ').html_safe %>
            <% else %>
              <%= link_to @statement[:invoice_ids], invoice_path(@statement[:invoice_ids]) %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>
<%#= @statement %>
<%#= @statement[:invoice_ids].kind_of?(Array) %>

app/views/payments/index.html.erb
<% provide(:title, "Payment History") %>
<div class="page-header">
  <h1><i class="fa fa-book fa-fw"></i> Payment History</h1>
</div>
<table class="table table-condensed">
  <tr>
    <th>Payment ID</th>
    <th>Date</th>
    <th>Status</th>
    <th>Amount</th>
    <th>Balance</th>
    <th>Method</th>
    <th>Authorization code</th>
  </tr>

  <%  @payments.each do |payment| %>
    <tr>
        <td><%= link_to payment[:id], payment_path(payment[:id])  %></td>
        <td><%= time_format payment[:payment_date] %></td>
        <td><%= result(payment[:result_id]) %></td>
        <td><%= number_to_currency(payment[:amount], precision: 2) %></td>
        <td><%= number_to_currency(payment[:balance].to_f,   precision: 2)%></td>
        <td><%= payment[:method]%></td>
        <% if payment[:authorization_id] %>
         <td><%= payment[:authorization_id][:code1] %></td>
        <% end %>
    </tr>
  <% end %>


</table>

app/views/payments/show.html.erb
<% provide(:title, "Payment details") %>

<div class="row">
  <div class="page-header">
    <h1><i class="fa fa-book fa-fw"></i> Payment Details</h1>
  </div>
  <%= render 'payment_detail', statement: @statement %>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Try for a new payment</h3>
      </div>
      <div class="panel-body">


          <div class="col-xs-6">
            <%= link_to '<i class="fa fa-credit-card"></i> Pay with credit card'.html_safe, new_credit_path, class: "btn pull-left btn-yellow" %>
          </div>
          <div class="col-xs-6">
            <%= link_to '<i class="fa fa-university"></i> Pay with ACH(Bank)'.html_safe, new_bank_path, class: "btn pull-right btn-yellow" %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/show.pdf.erb
<div class="container">
      <div class="row">
        <div class="col-xs-6">
          <h1>
            <a href="#">
            <%= wicked_pdf_image_tag('entity-10.png')%>

            </a>
          </h1>
        </div>
        <div class="col-xs-6 text-right">
          <h1>INVOICE</h1>
          <h1><small>Invoice # <%= @user.invoice[:number]%></small></h1>
          <h3><small>Due date # <%= time_format @user.invoice[:due_date] %></small></h3>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>From: <a href="#">KITCARSON TECHNOLOGY</a></h4>
            </div>
            <div class="panel-body">
              <p>
                Address:  116 Cruz Alta Road, Taos, NM 87571<br>
                Call: 575) 758-4838<br>
                Email: billing@kitcarson.net<br>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-5 col-xs-offset-2 text-right">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>To : <a href="#"><%= full_name(@user.contact[:first_name], @user.contact[:last_name]) %>  </a></h4>
            </div>
            <div class="panel-body">
              <p>
                Address : <%= @user.contact[:address1] %>,  <%= @user.contact[:address2] %><br>
                Details : <%= "#{@user.contact[:city]}- #{@user.contact[:postal_code] } , USA " %><br>
                Phone : <%= "#{@user.contact[:phone_country_code]} - #{@user.contact[:phone_area_code]} - #{@user.contact[:phone_number]}"  %></br>
                Email : <%= @user.contact[:email] %>  <br>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- / end client details section -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>
              <h4>Item ID</h4>
            </th>
            <th>
              <h4>Description</h4>
            </th>
            <th>
              <h4>Hrs/Qty</h4>
            </th>
            <th>
              <h4>Rate/Price</h4>
            </th>
            <th>
              <h4>Sub Total</h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <% i = 0 %>
          <% subtotal= 0 %>
          <% num = @items.length  %>
          <% while i < num %>

          <tr>

            <td><%= @items[i][:item_id]%></td>
            <td><a href="#"><%= @items[i][:description]%></a></td>
            <td class="text-right"><%= @items[i][:quantity].to_i %></td>
            <td class="text-right"><%= number_to_currency( @items[i][:price].to_f, precision: 2 ) %></td>
            <td class="text-right"><%= number_to_currency(@items[i][:amount].to_f, precision: 2 ) %></td>
          </tr>

           <% subtotal += @items[i][:amount].to_f  %>
           <%  i += 1 %>
          <% end %>

        </tbody>
      </table>
      <div class="row text-right">
        <div class="col-xs-2 col-xs-offset-8">
          <p>
            <strong>
            Sub Total : <br>
            TAX : <br>
            Total : <br>
            </strong>
          </p>
        </div>
        <div class="col-xs-2">
          <strong>
          <%= number_to_currency(subtotal, precision: 2) %> <br>
          <% @tax.each do |tax| %>
            <% tax = tax[:amount].to_f %>

            <%= number_to_currency(tax) %><br>
            <% total = subtotal + tax %>
            <%= number_to_currency(total, precision: 2) %><br>
          <% end %>
          <%#= (subtotal + tax).to_f %><br>
          </strong>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-5">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4>Account Info</h4>
            </div>
            <div class="panel-body">
              <p>Account Number : <%= @user.userid %></p>
              <p>Balance : <%= number_to_currency(@user.invoice[:balance].to_f,   precision: 2)%></p>
              <p>Previous Due: <%=  number_to_currency(@user.invoice[:carried_balance].to_f ,  precision: 2)%></p>
              <p>Status : <%= status @user.invoice[:status_id]%></p>

            </div>
          </div>
        </div>
        <div class="col-xs-7">
          <div class="span7">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h4>Contact Details</h4>
              </div>
              <div class="panel-body">
                <p>
                  Email : billing@kitcarson.net <br><br>
                  Billing : <a href="https://nbilling.imeet.biz">Pay your bill</a><br> <br>
                  Phone : +1 334 8948732</a>
                </p>
                <h4>Payment should be made by Bank Transfer, Credit card OR Cash</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/payments/statement.html.erb
<% provide(:title, "Payment details") %>
<div class="page-header">
  <h1><i class="fa fa-book fa-fw"></i> Payment Details</h1>
</div>
<%= render 'payment_details', statement: @statement %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Try for a new payment</h3>
      </div>
      <div class="panel-body">


          <div class="col-xs-6">
            <%= link_to '<i class="fa fa-credit-card"></i> Pay with credit card'.html_safe, new_credit_path, class: "btn pull-left btn-yellow" %>
          </div>
          <div class="col-xs-6">
            <%= link_to '<i class="fa fa-university"></i> Pay with ACH(Bank)'.html_safe, new_bank_path, class: "btn pull-right btn-yellow" %>
          </div>
      </div>
    </div>
  </div>
</div>